Student Marks Analysis System using NumPy.

In [2]:
# import
import numpy as np

In [3]:
#Dataset : student_names and marks
students = np.array(["Amit", "Rahul", "Priya", "Sneha", "Vikas",
                     "Neha", "Rohit", "Pooja", "Akash", "Kiran"])
marks = np.array([78, 45, 92, 67, 35, 88, 56, 74, 95, 62])

In [4]:
#Part 1 — Basic Array Information
print("Number of students :", len(students))
print("Dimensions         :", marks.ndim)
print("Shape              :", marks.shape)
print("Size               :", marks.size)
print("Data type          :", marks.dtype)

Number of students : 10
Dimensions         : 1
Shape              : (10,)
Size               : 10
Data type          : int64


In [5]:
#Part 2 — Sorting Operations
print("Ascending  :", np.sort(marks))               
print("Descending :", np.sort(marks)[::-1])

idx = np.argsort(marks) 
print(idx)
print("\nStudents sorted by marks (low to high):")
for n, m in zip(students[idx], marks[idx]):
    print(f"{n:<8} {m}")

print("\nTop 3 students:")
top3 = idx[::-1][:3] 
print(top3)
for n, m in zip(students[top3], marks[top3]):
    print(f"{n:<8} {m}")

print("\nLowest 3 students:")
low3 = idx[:3] 
print(low3)                                     
for n, m in zip(students[low3], marks[low3]):
    print(f"{n:<8} {m}")

Ascending  : [35 45 56 62 67 74 78 88 92 95]
Descending : [95 92 88 78 74 67 62 56 45 35]
[4 1 6 9 3 7 0 5 2 8]

Students sorted by marks (low to high):
Vikas    35
Rahul    45
Rohit    56
Kiran    62
Sneha    67
Pooja    74
Amit     78
Neha     88
Priya    92
Akash    95

Top 3 students:
[8 2 5]
Akash    95
Priya    92
Neha     88

Lowest 3 students:
[4 1 6]
Vikas    35
Rahul    45
Rohit    56


In [6]:
# Part 3 — Searching Operations
print("Task 1 - Marks > 70 :", students[marks > 70])
print("Task 2 - Marks < 50 :", students[marks < 50])
print("Task 3 - argwhere (marks > 80):", np.argwhere(marks > 80).flatten())
print("Task 4 - nonzero indices      :", np.nonzero(marks)[0])
print("Task 5 - count (marks > 60)   :", np.count_nonzero(marks > 60))

sorted_marks = np.sort(marks)
print(sorted_marks)
print("Task 6 - searchsorted for 70  :", np.searchsorted(sorted_marks, 70))

mask = np.isin(marks, [45, 67, 95])                 
print("Task 7 - isin [45,67,95]      :", students[mask], marks[mask])

Task 1 - Marks > 70 : ['Amit' 'Priya' 'Neha' 'Pooja' 'Akash']
Task 2 - Marks < 50 : ['Rahul' 'Vikas']
Task 3 - argwhere (marks > 80): [2 5 8]
Task 4 - nonzero indices      : [0 1 2 3 4 5 6 7 8 9]
Task 5 - count (marks > 60)   : 7
[35 45 56 62 67 74 78 88 92 95]
Task 6 - searchsorted for 70  : 5
Task 7 - isin [45,67,95]      : ['Rahul' 'Sneha' 'Akash'] [45 67 95]


In [7]:
# Part 4 — Conditional Operations
result = np.where(marks >= 40, "Pass", "Fail")
print("Task 1 - Pass/Fail:")
print(f"{'Student':<8} {'Marks':<6} Result")
for n, m, r in zip(students, marks, result):
    print(f"{n:<9} {m:<6} {r}")

print("\nTask 2 - Passed students:", students[marks >= 40]) 
print("Task 3 - Failed students:", students[marks < 40])

# Task 4 - np.select - grade
conditions = [marks < 40,
              (marks >= 40) & (marks <= 59),
              (marks >= 60) & (marks <= 74),
              (marks >= 75) & (marks <= 89),
              (marks >= 90) & (marks <= 100)]
grades = np.select(conditions, ["Fail", "C", "B", "A", "A+"], default="Invalid")
print("\nTask 4 - Grades:")
print(f"{'Student':<8} {'Marks':<6} Grade")
for n, m, g in zip(students, marks, grades):
    print(f"{n:<8} {m:<6} {g}")

# Task 5 - invalid marks clip karne (0 te 100)
invalid = np.array([78, 45, 110, 67, -5, 88])
print("\nTask 5 - Original :", invalid)
print("         Clipped  :", np.clip(invalid, 0, 100))

# Task 6 - Logical AND (60 <= marks <= 80)
and_mask = np.logical_and(marks >= 60, marks <= 80)
print("\nTask 6 - marks 60 to 80:", students[and_mask], marks[and_mask])

# Task 7 - Logical OR (marks < 40 ki > 90)
or_mask = np.logical_or(marks < 40, marks > 90)
print("Task 7 - marks <40 or >90:", students[or_mask], marks[or_mask])


Task 1 - Pass/Fail:
Student  Marks  Result
Amit      78     Pass
Rahul     45     Pass
Priya     92     Pass
Sneha     67     Pass
Vikas     35     Fail
Neha      88     Pass
Rohit     56     Pass
Pooja     74     Pass
Akash     95     Pass
Kiran     62     Pass

Task 2 - Passed students: ['Amit' 'Rahul' 'Priya' 'Sneha' 'Neha' 'Rohit' 'Pooja' 'Akash' 'Kiran']
Task 3 - Failed students: ['Vikas']

Task 4 - Grades:
Student  Marks  Grade
Amit     78     A
Rahul    45     C
Priya    92     A+
Sneha    67     B
Vikas    35     Fail
Neha     88     A
Rohit    56     C
Pooja    74     B
Akash    95     A+
Kiran    62     B

Task 5 - Original : [ 78  45 110  67  -5  88]
         Clipped  : [ 78  45 100  67   0  88]

Task 6 - marks 60 to 80: ['Amit' 'Sneha' 'Pooja' 'Kiran'] [78 67 74 62]
Task 7 - marks <40 or >90: ['Priya' 'Vikas' 'Akash'] [92 35 95]


In [8]:
# Part 5 — Statistical Analysis
print("Total marks    :", np.sum(marks))
print("Average        :", np.mean(marks))
print("Median         :", np.median(marks))
print("Minimum        :", np.min(marks))
print("Maximum        :", np.max(marks))
print("Std deviation  :", np.std(marks))
print("Variance       :", np.var(marks))
print("25th percentile:", np.percentile(marks, 25))
print("50th percentile:", np.percentile(marks, 50))
print("75th percentile:", np.percentile(marks, 75))
print("Index of highest:", np.argmax(marks))
print("Index of lowest :", np.argmin(marks))
print("Highest student :", students[np.argmax(marks)])
print("Lowest student  :", students[np.argmin(marks)])

Total marks    : 692
Average        : 69.2
Median         : 70.5
Minimum        : 35
Maximum        : 95
Std deviation  : 19.041008376659047
Variance       : 362.56
25th percentile: 57.5
50th percentile: 70.5
75th percentile: 85.5
Index of highest: 8
Index of lowest : 4
Highest student : Akash
Lowest student  : Vikas


In [11]:
# Part 6 — Missing Value Handling
m_nan = np.array([78, 45, np.nan, 67, 35, np.nan, 56, 74, 95, 62])
print("Array with NaN :", m_nan)
print("isnan          :", np.isnan(m_nan))
print("NaN count      :", np.isnan(m_nan).sum())
print("nanmean        :", np.nanmean(m_nan))
print("nanmedian      :", np.nanmedian(m_nan))
print("nansum         :", np.nansum(m_nan))
print("nanmin         :", np.nanmin(m_nan))
print("nanmax         :", np.nanmax(m_nan))
print("nanstd         :", np.nanstd(m_nan))

filled = np.where(np.isnan(m_nan), np.nanmean(m_nan), m_nan)    
print("NaN replaced with mean:", filled)

Array with NaN : [78. 45. nan 67. 35. nan 56. 74. 95. 62.]
isnan          : [False False  True False False  True False False False False]
NaN count      : 2
nanmean        : 64.0
nanmedian      : 64.5
nansum         : 512.0
nanmin         : 35.0
nanmax         : 95.0
nanstd         : 17.804493814764857
NaN replaced with mean: [78. 45. 64. 67. 35. 64. 56. 74. 95. 62.]


In [12]:
# Part 7: Infinity Handling 
inf_arr = np.array([10, 20, np.nan, np.inf, -np.inf, 50])
print("Array    :", inf_arr)
print("isinf    :", np.isinf(inf_arr))
print("isfinite :", np.isfinite(inf_arr))

Array    : [ 10.  20.  nan  inf -inf  50.]
isinf    : [False False False  True  True False]
isfinite : [ True  True False False False  True]


In [13]:
# Part 8: Random Number Generation  
rng = np.random.default_rng(42)
 
print("Task 1 - Random marks     :", rng.integers(1, 101, size=10))
print("Task 2 - Random floats    :", rng.random(5))
 
courses = np.array(["Python", "Java", "Data Science", "Data Analytics"])
print("Task 3 - Random courses   :", rng.choice(courses, 5))   # repeat challa
print("Task 4 - Random students  :", rng.choice(students, 3, replace=False))
print("Task 5 - Normal (60,10)   :", rng.normal(60, 10, 10))
print("Task 6 - Uniform (10,20)  :", rng.uniform(10, 20, 5))
print("Task 7 - Binomial (10,0.5):", rng.binomial(10, 0.5, 10))
print("Task 8 - Poisson (lam=3)  :", rng.poisson(3, 10))
 
shuffled = students.copy()          # original la dhakka nako mhanun copy
rng.shuffle(shuffled)
print("Task 9 - Shuffled copy    :", shuffled)
print("         Original intact  :", students)
 
print("Task 10 - Original :", students)
print("          Permuted :", rng.permutation(students))

Task 1 - Random marks     : [ 9 78 66 44 44 86  9 70 21 10]
Task 2 - Random floats    : [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
Task 3 - Random courses   : ['Data Science' 'Java' 'Python' 'Data Analytics' 'Data Analytics']
Task 4 - Random students  : ['Akash' 'Neha' 'Sneha']
Task 5 - Normal (60,10)   : [51.40707537 63.68750784 50.41117399 68.78450301 59.50074089 58.15137636
 53.19070456 72.22541339 58.45470518 55.71672178]
Task 6 - Uniform (10,20)  : [11.94638708 14.66721004 10.43803766 11.54289492 16.83048953]
Task 7 - Binomial (10,0.5): [6 8 4 4 5 4 3 5 4 6]
Task 8 - Poisson (lam=3)  : [6 2 1 6 2 5 0 2 2 3]
Task 9 - Shuffled copy    : ['Vikas' 'Amit' 'Akash' 'Neha' 'Pooja' 'Rohit' 'Priya' 'Kiran' 'Rahul'
 'Sneha']
         Original intact  : ['Amit' 'Rahul' 'Priya' 'Sneha' 'Vikas' 'Neha' 'Rohit' 'Pooja' 'Akash'
 'Kiran']
Task 10 - Original : ['Amit' 'Rahul' 'Priya' 'Sneha' 'Vikas' 'Neha' 'Rohit' 'Pooja' 'Akash'
 'Kiran']
          Permuted : ['Kiran' 'Vikas' 'Rohit' 

In [14]:
# Part 9 - File Handling
np.save("student_marks.npy", marks)          # Task 1
print("Task 2 - Loaded npy:", np.load("student_marks.npy"))
 
np.savez("student_data.npz", students=students, marks=marks)   # Task 3
data = np.load("student_data.npz")                             # Task 4
print("Task 4 - Names :", data["students"])
print("         Marks :", data["marks"])
 
np.savetxt("marks.csv", marks, delimiter=",", fmt="%d")   # Task 5
print("Task 6 - Loaded CSV:", np.loadtxt("marks.csv", delimiter=","))
 
arr2d = np.array([[78, 45, 92],
                  [67, 35, 88],
                  [56, 74, 95]])                          # Task 7
np.savetxt("student_subject_marks.csv", arr2d, delimiter=",", fmt="%d")
print("Task 7 - 2D CSV loaded:")
print(np.loadtxt("student_subject_marks.csv", delimiter=","))

Task 2 - Loaded npy: [78 45 92 67 35 88 56 74 95 62]
Task 4 - Names : ['Amit' 'Rahul' 'Priya' 'Sneha' 'Vikas' 'Neha' 'Rohit' 'Pooja' 'Akash'
 'Kiran']
         Marks : [78 45 92 67 35 88 56 74 95 62]
Task 6 - Loaded CSV: [78. 45. 92. 67. 35. 88. 56. 74. 95. 62.]
Task 7 - 2D CSV loaded:
[[78. 45. 92.]
 [67. 35. 88.]
 [56. 74. 95.]]


In [16]:
# Final Task - Student Report
# =========================================================
print("\n===== Student Report =====")
print(f"{'Student':<10}{'Marks':<8}Grade")
print("-" * 27)
for n, m, g in zip(students, marks, grades):
    print(f"{n:<10}{m:<8}{g}")
print("-" * 27)

print("Total Students  :", students.size)
print("Total Marks     :", marks.sum())
print("Average Marks   :", marks.mean())
print("Highest Marks   :", marks.max())
print("Lowest Marks    :", marks.min())
print("Passed Students :", np.count_nonzero(marks >= 40))
print("Failed Students :", np.count_nonzero(marks < 40))


===== Student Report =====
Student   Marks   Grade
---------------------------
Amit      78      A
Rahul     45      C
Priya     92      A+
Sneha     67      B
Vikas     35      Fail
Neha      88      A
Rohit     56      C
Pooja     74      B
Akash     95      A+
Kiran     62      B
---------------------------
Total Students  : 10
Total Marks     : 692
Average Marks   : 69.2
Highest Marks   : 95
Lowest Marks    : 35
Passed Students : 9
Failed Students : 1
