### Function Arrays

In [1]:
import numpy as np

In [2]:
a1 = np.zeros((5,2))
print(a1)
print()

a2 = np.ones((2,4))
print(a2)
print()

a3 = np.full((2,3),8)
print(a3)

a4 = np.arange(1,11,2)
print(a4)

a5 = np.eye(4)
print(a5)

a6 = np.linspace(1, 10, 5)
print(a6)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[8 8 8]
 [8 8 8]]
[1 3 5 7 9]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 1.    3.25  5.5   7.75 10.  ]


In [3]:
#Math Operations:
a1 = np.array([5,6,7,8])
a2 = np.array([1,2,3,4])

np.subtract(a1,a2)     # element-wise subtraction -> [4 4 4 4]
np.divide(a1,a2)       # element-wise division -> [5. 3. 2.33 2.]
np.multiply(a1,a2)     # element-wise multiplication -> [5 12 21 32]

array([ 5, 12, 21, 32])

In [4]:
#Statistics Functions:
a1 = np.array([5,6,7,8])

np.min(a1)        
np.max(a1)      
np.median(a1)     
np.std(a1)        
np.var(a1)        

np.float64(1.25)

In [5]:
# 1. numpy.power() — Raises elements to a power
a1 = np.array([2,3,4,5])
np.power(a1, 2)          # raises each element to power 2 (square)

# 2. numpy.sqrt() — Calculates square root
a2 = np.array([4,9,16,25])
np.sqrt(a2)

# 3. numpy.abs() — Absolute value (removes negative sign)
a3 = np.array([-5,6,-7,8])
np.abs(a3)

array([5, 6, 7, 8])

In [6]:
# reshape():

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

# ---------- Reshape into 1-D ----------
a1 = arr.reshape((12,))
print("1-D Array:")
print(a1)
print(a1.ndim)      # Output: 1

print()

# ---------- Reshape into 2-D ----------
a2 = arr.reshape((3,4))
print("2-D Array:")
print(a2)
print(a2.ndim)      # Output: 2

print()

# ---------- Reshape into 3-D ----------
a3 = arr.reshape((2,2,3))
print("3-D Array:")
print(a3)
print(a3.ndim)      # Output: 3

1-D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

2-D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2

3-D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [7]:
# flatten() & ravel() Function:----->>

# ---------- Original Array ----------
a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
print("-" * 40)

# ---------- flatten() - Creates a COPY ----------
af = a1.flatten()
print(af)          # [1 2 3 4 5 6]     # convert into 1D

af[1] = 999         # changing flatten's element
print(af)           # [  1 999   3   4   5   6]
print(a1)           # Original a1 UNCHANGED (safe)
print("-" * 40)

# ---------- ravel() - Creates a VIEW ----------
ar = a1.ravel()
print(ar)           # [1 2 3 4 5 6]    # convert into 1D

ar[1] = 888          # changing ravel's element
print(ar)            # [  1 888   3   4   5   6]
print(a1)            # Original a1 CHANGED too!

[[1 2]
 [3 4]
 [5 6]]
----------------------------------------
[1 2 3 4 5 6]
[  1 999   3   4   5   6]
[[1 2]
 [3 4]
 [5 6]]
----------------------------------------
[1 2 3 4 5 6]
[  1 888   3   4   5   6]
[[  1 888]
 [  3   4]
 [  5   6]]


In [8]:
# copy() & view() Function:---->>
# ==================================================
# COPY() EXAMPLE
# ==================================================
a1 = np.array([1,2,3,4])
a2 = a1.copy()          # creates an independent copy of a1

print(a1)               # [1 2 3 4]
print()
print(a2)               # [1 2 3 4]

a2[-1] = 7777            # changing the last element of the COPY

print(a2)                # [   1    2    3 7777]
print(a1)                # [1 2 3 4] -> original a1 remains UNCHANGED (safe)

print("=" * 40)

# ==================================================
# VIEW() EXAMPLE
# ==================================================
a1 = np.array([1,2,3,4])
a2 = a1.view()           # creates a view (linked to a1's memory)

print(a1)                 # [1 2 3 4]
print()
print(a2)                 # [1 2 3 4]

a2[0] = 3333               # changing the first element of the VIEW

print(a2)                  # [3333    2    3    4]
print(a1)                  # [3333    2    3    4] -> original a1 CHANGES too!

[1 2 3 4]

[1 2 3 4]
[   1    2    3 7777]
[1 2 3 4]
[1 2 3 4]

[1 2 3 4]
[3333    2    3    4]
[3333    2    3    4]


In [9]:
# stack() Function:---->>

a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

# ==================================================
# np.stack() with axis=0 (stacks row-wise, one below another)
# ==================================================
ar = np.stack((a1,a2), axis=0)
print(ar)
# Output:
# [[1 2 3 4]
#  [5 6 7 8]]

print("=" * 40)

# ==================================================
# np.stack() with axis=1 (stacks column-wise, side by side)
# ==================================================
ar = np.stack((a1,a2), axis=1)
print(ar)
# Output:
# [[1 5]
#  [2 6]
#  [3 7]
#  [4 8]]

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [10]:
# hstack() vs vstack() - Functions:------->>
# ==================================================
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

# ---------- 1. hstack() - Horizontal Stack ----------
# Joins arrays SIDE BY SIDE (in the same row)
# Result stays 1-D (if inputs are 1-D)
h = np.hstack((a1,a2))
print(h)
# Output: [1 2 3 4 5 6 7 8]

print("=" * 40)

# ---------- 2. vstack() - Vertical Stack ----------
# Joins arrays ONE ON TOP OF ANOTHER (as separate rows)
# Result becomes 2-D (each array = one row)
v = np.vstack((a1,a2))
print(v)
# Output:
# [[1 2 3 4]
#  [5 6 7 8]]

print("=" * 40)

# ---------- 3. Same functions on 2-D arrays ----------
b1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])

h2 = np.hstack((b1,b2))
print(h2)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]

v2 = np.vstack((b1,b2))
print(v2)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
# ==================================================
# split() vs hsplit() vs vsplit() :--------->>
# ==================================================

# ---------- 1. split() - General Split ----------
# Splits a 1-D array into EQUAL parts
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(a1)

ar = np.split(a1, 2)      # split into 2 equal parts
print(ar)
a1_part = ar[0]
print(a1_part)             # [1 2 3 4 5]

a2_part = ar[1]
print(a2_part)              # [6 7 8 9 10]

print("=" * 40)

# ---------- 2. hsplit() - Horizontal Split ----------
# Splits a 2-D array COLUMN-WISE (splits side by side into left-right parts)
b1 = np.array([[1,2,3,4],[6,7,8,9]])
print(b1)

h = np.hsplit(b1, 2)
print(h)
# Output:
# [array([[1, 2],
#         [6, 7]]),
#  array([[3, 4],
#         [8, 9]])]

print("=" * 40)

# ---------- 3. vsplit() - Vertical Split ----------
# Splits a 2-D array ROW-WISE (splits top-bottom into separate rows)
c1 = np.array([[1,2,3,4],[6,7,8,9]])
print(c1)

v = np.vsplit(c1, 2)
print(v)
# Output:
# [array([[1, 2, 3, 4]]),
#  array([[6, 7, 8, 9]])]

[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2 3 4]
 [6 7 8 9]]
[array([[1, 2],
       [6, 7]]), array([[3, 4],
       [8, 9]])]
[[1 2 3 4]
 [6 7 8 9]]
[array([[1, 2, 3, 4]]), array([[6, 7, 8, 9]])]


In [12]:
# ==================================================
# split() vs hsplit() vs vsplit() on a 2-D Array
# ==================================================

arr = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
print(arr)

print("=" * 40)

# ---------- 1. split() - General Split (default: axis=0, row-wise) ----------
# Splits the array into EQUAL parts along rows (same as vsplit by default)
s = np.split(arr, 2)
print(s)
# Output:
# [array([[1, 2, 3, 4],
#         [5, 6, 7, 8]]),
#  array([[ 9, 10, 11, 12],
#         [13, 14, 15, 16]])]

print("=" * 40)

# ---------- 2. hsplit() - Horizontal Split (column-wise) ----------
# Splits the array LEFT-RIGHT (splits columns)
h = np.hsplit(arr, 2)
print(h)
# Output:
# [array([[ 1,  2],
#         [ 5,  6],
#         [ 9, 10],
#         [13, 14]]),
#  array([[ 3,  4],
#         [ 7,  8],
#         [11, 12],
#         [15, 16]])]

print("=" * 40)

# ---------- 3. vsplit() - Vertical Split (row-wise) ----------
# Splits the array TOP-BOTTOM (splits rows)
v = np.vsplit(arr, 2)
print(v)
# Output:
# [array([[1, 2, 3, 4],
#         [5, 6, 7, 8]]),
#  array([[ 9, 10, 11, 12],
#         [13, 14, 15, 16]])]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
