## Array

In [1]:
print("Hello Shiv")

Hello Shiv


In [2]:
import numpy

In [3]:
arr = numpy.array([11,22,33,44,55,66,77,88,99])  # [11 22 33 44 55 66 77 88 99]
# arr = numpy.array([11,22,33,44,55,66,77,88,99,"raj"])  # ['11' '22' '33' '44' '55' '66' '77' '88' '99' 'raj']
# arr = numpy.array([11,22,33,44,55,66,77,88,99,9.0]) #[11. 22. 33. 44. 55. 66. 77. 88. 99.  9.]
print(arr)       # A numpy array is homogeneous — all elements inside it must be of the same data type.

[11 22 33 44 55 66 77 88 99]


In [4]:
arr = numpy.array([11,22,33,44,55])
print(arr)
# Output: [11 22 33 44 55]

[11 22 33 44 55]


In [5]:
l = [11,22,33,44,55]
inc = []
for num in l:
    inc.append(num+5)
print(inc)
# Output: [16, 27, 38, 49, 60]

[16, 27, 38, 49, 60]


In [6]:
print(arr+5)

[16 27 38 49 60]


In [7]:
# ---------- 0-D Array (Scalar) ----------
ar0 = numpy.array(78)      # stores a single value, has no dimension
print(ar0) 
print(ar0.ndim)            # ndim checks the dimension -> Output: 0 (0-D array)

78
0


In [8]:
# ---------- 1-D Array (Vector) ----------
ar1 = numpy.array([10,20,30,40])   # multiple values in a single row (list)
print(ar1)   
print(ar1.ndim)                       
# ar1.ndim would give output 1 (1-D array)

[10 20 30 40]
1


In [9]:
# ---------- 2-D Array (Matrix) ----------
ar2 = numpy.array([[11,22],[33,44],[55,66]])   # rows and columns (list of lists)
print(ar2)
print(ar2.ndim)
# Output:
# [[11 22]
#  [33 44]
#  [55 66]]
# ar2.ndim would give output 2 (2-D array)

[[11 22]
 [33 44]
 [55 66]]
2


In [10]:
# ---------- 3-D Array ----------
ar3 = numpy.array([
                    [[1,2,3,4], [5,6,7,8], [11,22,33,44]],
                    [[12,13,14,15], [21,32,55,66], [1,2,3,4]]
                  ])

print(ar3)
print(ar3.ndim)
print(ar3.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [11 22 33 44]]

 [[12 13 14 15]
  [21 32 55 66]
  [ 1  2  3  4]]]
3
(2, 3, 4)


In [11]:
# Array Properties (ndim, shape, size, dtype):------>>

arr = numpy.array([[11, 22, 33], [44, 55, 66]])

print(arr)              # prints the array itself

print(arr.ndim)         # checks number of dimensions -> Output: 2

print(arr.shape)        # checks structure (rows, columns) -> Output: (2, 3)

print(arr.size)         # checks total number of elements -> Output: 6

print(arr.dtype)        # checks data type of elements -> Output: int64

print(type(arr))        # confirms it is a numpy ndarray object

[[11 22 33]
 [44 55 66]]
2
(2, 3)
6
int64
<class 'numpy.ndarray'>
