### Indexing and Slicing:


In [2]:
import numpy as np

In [3]:
# Indexing:----->
a1 = np.array([1,2,3,4,5,6])
print(a1)
#Access
#Array[index]
print(a1[2])

[1 2 3 4 5 6]
3


In [4]:
a1 = np.array([[1,2,3], [4,5,6]])
print(a1)
print()
print(a1[0])
print()
print(a1[1][2])
print()
print(a1[0,1])


[[1 2 3]
 [4 5 6]]

[1 2 3]

6

2


In [5]:
# Slicing:-------->>
a1 = np.array([1,2,3,4,5,6])
a1 = np.array([11,22,33,44,55,66])
print(a1)
#arr[startindex : endindex:stepvalue]
a1[1:-2:1]
a1[-2:1:-1]

[11 22 33 44 55 66]


array([55, 44, 33])

In [6]:
a2 = np.array([[11,22,33,44],[55,66,77,88]])
print(a2)
print()
print(a2[0][1:-1:1])
print()
print(a2[1,0:-1:1])

[[11 22 33 44]
 [55 66 77 88]]

[22 33]

[55 66 77]


In [7]:
arr = np.array([[11,22,33,44],[1,2,3,4],[21,32,43,54]])
print(arr)
print()
print(arr[:-1,1:-1])

[[11 22 33 44]
 [ 1  2  3  4]
 [21 32 43 54]]

[[22 33]
 [ 2  3]]


In [8]:
arr = np.array([[11,22,33,44],[1,2,3,4],[21,32,43,54]])
print(arr)

[[11 22 33 44]
 [ 1  2  3  4]
 [21 32 43 54]]


In [9]:
print(arr[1])
print(arr[-1,2])
print(arr[1,1:])
print(arr[-1,-2::-1])
print(arr[:,2])
print(arr[1:,1])
print(arr[:2,2:])
print(arr[::-1,0])

[1 2 3 4]
43
[2 3 4]
[43 32 21]
[33  3 43]
[ 2 32]
[[33 44]
 [ 3  4]]
[21  1 11]


Methods and Function:

In [10]:
#Sort
a1 = np.array([1,4,5,2,3,6])
print(a1)
a2 = np.sort(a1)         # Function - new obj return
print(a2)

[1 4 5 2 3 6]
[1 2 3 4 5 6]


In [11]:
#Sort
a1 = np.array([1,4,5,2,3,6])
a1.sort()
print(a1)
print(a1 [::-1])               # Method - original obj change

[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [12]:
#argsort
a1 = np.array([1,4,5,2,3,6])
np.argsort(a1)

array([0, 3, 4, 1, 2, 5])

In [13]:
emp= np.array(['raj','pavan','ram','kunal'])
sal = np.array([22000,11000,33000,12000])
ar = np.argsort(sal)
for index in ar:
    print(emp[index])

pavan
kunal
raj
ram


In [14]:
#Where
emp= np.array(['raj','pavan','ram','kunal'])
sal = np.array([22000,11000,33000,12000])
print(np.where(sal>20000)) # return index
sal[np.where(sal>20000)]   # return value

(array([0, 2]),)


array([22000, 33000])

In [ ]:
#append
emp= np.array(['raj','pavan','ram','kunal'])
sal = np.array([22000,11000,33000,12000])
emp1 = np.append(emp,"vaibhav")
print(emp1)

['raj' 'pavan' 'ram' 'kunal' 'vaibhav']


In [23]:
#insert
sal = np.array([22000,11000,33000,12000])
np.insert(sal,2,10000)

array([22000, 11000, 10000, 33000, 12000])

In [28]:
#delete
np.delete(emp,3)

array(['raj', 'pavan', 'ram'], dtype='<U5')

In [ ]:
#save
emp= np.array(['raj','pavan','ram','kunal'])
np.save("emp_data.npy",emp)

In [33]:
#load
data = np.load("emp_data.npy")
data

array(['raj', 'pavan', 'ram', 'kunal'], dtype='<U5')

In [35]:
#where - condition
marks = np.array([10,23,45,50,60,70,80,90])
np.where(marks>40,"Pass","Fail")

array(['Fail', 'Fail', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass'],
      dtype='<U4')

In [ ]:
#logical_and
np.logical_and(marks>30,marks<65)

array([False, False,  True,  True,  True, False, False, False])